"""empty message

Revision ID: 13b921686d74
Revises: 
Create Date: 2022-05-16 14:16:53.253854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b921686d74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.Text(), nullable=False),
    sa.Column('lastname', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bills',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('date_of_issue', sa.DateTime(), nullable=False),
    sa.Column('amount_due', sa.Numeric(), nullable=False),
    sa.Column('fees', sa.Numeric(), nullable=True),
    sa.Column('interest', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_number', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('past_due', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('totals',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_totals', sa.Numeric(), nullable=False),
    sa.Column('tax_totals', sa.Numeric(), nullable=False),
    sa.Column('tax_year', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('receipts',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_total', sa.Numeric(), nullable=False),
    sa.Column('tax', sa.Numeric(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('transaction_number', sa.String(length=14), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('total_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['total_id'], ['totals._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('transaction_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('totals')
    op.drop_table('bills')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
