version: "3.8"
services:
  web:
    build: ./app
    # command: flask run --host=0.0.0.0 --port=8000
    command: gunicorn --bind 0.0.0.0:8000 -w 2 app:app
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:5000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}:/var/lib/data"
# docker exec -it [container_name] psql -U [username] -W [db_name]
