version: "3.8"
services:
  web:
    build: ./app
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    # networks:
    #   - default
    # depends_on:
    #   - postgres
    # - redis
  # [For development only]
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: receipt_manager
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #     PGUSER: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - "${PWD}:/docker-entrypoint-initdb.d/"
  #   networks:
  #     - default
  # [docker exec -it [container_name] psql -U [username] -W [db_name]]
  # redis:
  #   image: redis:latest
  #   restart: always
  #   command: redis-server --requirepass admin123
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - "${PWD}/redis-data:/data"
