version: "3.8"
services:
  web:
    build: ./app
    command: flask run --host=0.0.0.0 --port=5432
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    # environment:
    #   POSTGRES_USER: ${USER}
    #   POSTGRES_PASSWORD: ${PASSWORD}
    #   POSTGRES_DB: ${DB}
    #   PGUSER: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}:/var/lib/data"
# docker exec -it [container_name] psql -U [username] -W [db_name]
