version: "3.8"
services:
  web:
    build: ./app
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    networks:
      - default
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}/data/initdb/:/docker-entrypoint-initdb.d/"
    networks:
      - default
# docker exec -it [container_name] psql -U [username] -W [db_name]
