version: "3.8"
services:
  web:
    build: ./app
    command: flask run
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - DB_NAME=receipt_manager
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: receipt_manager
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}:/var/lib/app"
