version: "3.8"
services:
  # # [For development]
  # web:
  #   build: ./app
  #   restart: always
  #   volumes:
  #     - ./app:/usr/src/app/
  #   # ports:
  #   #   - 5000:5000
  #   expose:
  #     - 5000
  #   depends_on:
  #     - db-test
  # nginx:
  #   build: ./app/nginx
  #   restart: always
  #   volumes:
  #     - "${PWD}:/etc/nginx/templates"
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - web
  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: receipt_manager
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #     PGUSER: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - "${PWD}:/docker-entrypoint-initdb.d/"
  #   networks:
  #     - default
  #[For tests]
  db-test:
    image: postgres:latest
    restart: always
    container_name: test_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - 5433:5432
  # [docker exec -it [container_name] psql -U [username] -W [db_name]]
