version: "3.8"
services:
  web:
    build: ./app
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    networks:
      - default
    depends_on:
      - postgres
    # - redis
  # [For development]
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: stub_manager
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - 5432:5432
    volumes:
      - "${PWD}:/docker-entrypoint-initdb.d/"
    networks:
      - default
  #[For unit/integration testing]
  db-test:
    image: postgres:latest
    restart: always
    container_name: test_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - 5433:5432
  # [docker exec -it [container_name] psql -U [username] -W [db_name]]
