name: Receipt-Manager push

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Python version
        run: python -c "import sys; print(sys.version)"

      - name: Build containers
        run: docker-compose up -d

      - name: Install dependencies
        working-directory: ./app
        run: |
          python -m pip install --upgrade pip
          cd app pip install -r requirements.txt
          cd ..

      - name: Test with pytest-flask
        run: python -m pytest -v

      - name: Run the Python code in helloworld.py
        run: |
          echo "Running Python code"
          python app.py
