name: Receipt-Manager push

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    environment: RECEIPT_MANAGER_URI
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python version
        run: python -c "import sys; print(sys.version)"

      - name: Build containers
        run: docker-compose up -d
      - name: Check database log
        run: docker logs receipt-manager-db
      - name: Install dependencies
        working-directory: ./app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make migrations
        working-directory: ./app
        run: flask db upgrade

      - name: Test with pytest-flask
        run: python -m pytest -v
